# Generated by Django 4.2.6 on 2023-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='category',
        ),
        migrations.AddField(
            model_name='serial',
            name='categories',
            field=models.ManyToManyField(related_name='serials', to='series.category'),
        ),
    ]
