# Generated by Django 4.2.6 on 2023-10-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
