# Generated by Django 4.2.6 on 2023-10-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_remove_serial_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='ticket',
            new_name='serial',
        ),
    ]
