# Generated by Django 4.2.6 on 2023-10-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
