# Generated by Django 4.2.6 on 2023-10-13 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0007_alter_categorysubscription_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysubscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
