# Generated by Django 4.2.6 on 2023-10-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_userprofile'),
        ('series', '0008_alter_categorysubscription_owner'),
    ]

    operations = [
    ]
