# Generated by Django 4.2.6 on 2023-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_alter_categorysubscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='vendor_code',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
