# Generated by Django 4.2.6 on 2023-10-18 11:47

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', applications.account.models.CustomUserManager()),
            ],
        ),
    ]
