# Generated by Django 4.2.6 on 2023-10-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_confirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='confirmation_code',
            new_name='deletion_confirmation_code',
        ),
    ]
