# Generated by Django 4.2.6 on 2023-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_confirmation_code_customuser_deletion_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deletion_confirmation_code',
            field=models.CharField(max_length=100),
        ),
    ]
