# Generated by Django 4.2.6 on 2023-10-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_deletion_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deletion_confirmation_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
